### ISSUE TITLE
Append action erring on string with regex

### ISSUE THREAD

**Issue by bryantAXS** [amwmedia/plop#178]
I'm using the dashCase filter along with the append action and a string I have is apparently being recognized as a regex and erring. To be clear, it's not intended to be a regex.

Here's the action: 

```
actions.push({
  type: 'append',
  path: 'src/scripts/app.js',
  pattern: "(Components Loader -- DO NOT REMOVE COMMENT!)",
  template: '{handle: "[data-{{ dashCase name}}]", require: {{properCase name}} }\,',
});
```

Any thoughts on that one?

thanks!

**Comment by amwmedia** [comment]
fixed in v2.5.1

**Comment by jwrudzin** [comment]
This appears to be fixed for some inputs but not others.

Using the code and input from the original post, I'm still seeing the `Range out of order in character class` error. I'm running plop v2.5.3.
